data: "MEDS_all_20240910:1"

computes:
    default: "CPU-20-LP"
    pretrain: "GPU-A100-Single"
    finetune_cv: "GPU-A100-Single"

create_data:
    max_run_time: 5400 # 1h30m

create_outcomes:
    max_run_time: 1080 # 18m

prepare_training_data:
    max_run_time: 1500 # 25m

select_cohort:
    max_run_time: 200

pretrain:
    max_run_time: 3000 # 50m
    metrics:
        - type: "Val loss"
          max: 4
        - type: "Train loss"
          max: 4
        - type: "top1"
          min: 0.3

finetune_cv:
    max_run_time: 1200 = # 20m
    metrics:
        - type: "best.test.accuracy"
          child: "Fold 1"
          min: 0.96
        - type: "best.test.roc_auc"
          child: "Fold 1"
          min: 0.3

on_fail: "raise"
