logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  features: ./outputs/features
  tokenized: ./outputs/tokenized
  # tokenized_file: ...
  # tokenized_pids: ...
  
  ## optional
  # cohort: ... # path to cohort directory

## OUTPUTS
  prepared_data: ./outputs/pretraining/processed_data/ # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

data:
  type: "pretrain"
  predefined_splits: false # set to true if you want to use predefined splits for reproducibility. Expects a list (of length 1) of dicts with train, val created by select_cohort
  val_ratio: 0.2 # only used if predefined_splits is false
  truncation_len: 20
  min_len: 2
  predefined_splits: false # set to true if you want to use predefined splits for reproducibility. Expects a list (of length 1) of dicts with train, val created by select_cohort
  val_ratio: 0.2 # only used if predefined_splits is false
  
  # cutoff_date:
  #   year: 2020
  #   month: 1
  #   day: 1
