logging:
  level: INFO
  path: ./outputs/logs

paths:
  model: "./outputs/finetuning/bad_censoring"
  folds_dir: "./outputs/finetuning/processed_data/bad"
  test_data_dir: "./outputs/testing/held_out/processed_data/bad" 
  run_name: "evaluate"
  predictions: "./outputs/testing/held_out/predictions/bad_on_bad"

test_batch_size: 128

metrics:
  roc_auc: 
    _target_: sklearn.metrics.roc_auc_score

save_info: 
  sequence_length: 
    _target_: corebehrt.main.helper.evaluate_finetune.get_sequence_length